- alias: 'Siren-PÅ'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001ab5bab
      to: 'on'
    - platform: numeric_state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_burglar_2
      above: 0
  condition:
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_home
  action:   
    - service: switch.turn_on
      entity_id: switch.vision_zm1601eu_5_battery_operated_siren_switch

    - service: switch.turn_on
      entity_id: switch.vrum

    - service: switch.turn_on
      entity_id: switch.garage

    - service: notify.ios_jonas_iphone
      data:
        message: "LARM I FÖRRÅD UTLÖST"

- alias: 'Siren-AV'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.mytest
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.vision_zm1601eu_5_battery_operated_siren_switch

- alias: 'Trigger Siren'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_zw5_motion_sensor_sensor
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_alarm
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.vision_zm1601eu_5_battery_operated_siren_switch

- alias: 'Enable Alarm'
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.enable_alarm
      to: 'on'
  action:
    service: notify.emailsms
    data:
      title: 'Aktivera Larmet'
      message: '1'

- alias: 'Disable Alarm'
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.enable_alarm
      to: 'off'
  action:
    service: notify.emailsms
    data:
      message: '0'

- alias: 'Skalskydd'
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.enable_shell
      to: 'on'
  action:
    service: notify.emailsms
    data:
      message: '2'

- alias: 'Släck Altan'
  initial_state: True
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010b25c0
      action_type: free_fall
  action:
    service: homeassistant.turn_off
    entity_id: group.altan 

- alias: 'Spots På Altan'
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010b25c0
      action_type: shake_air
  action:
    service: homeassistant.turn_on
    entity_id: switch.altan_spot_x_3


- alias: 'Öppna Altandörr'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001ab5bab
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.altan_spot_x_3

#- alias: 'Hue på Kök'
#  trigger:
#    platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00010b25c0
#      action_type: rotate
#  action:
#    service: light.hue_activate_scene
#    data:
#      group_name: 'Kök'
#      scene_name: 'Bright'

- alias: 'If motion and dark turn on Hall'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d5914d
    from: 'off'
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_286c0788970f
    below: 150
  action:
    service: homeassistant.turn_on
    entity_id: switch.hall


- alias: 'If no motion for 10 minutes turn off Hall'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d5914d
    from: 'on'
    to: 'off'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.hall

- alias: 'Altan PÅ vid enkelklick'
  initial_state: True
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00019cd397
      click_type: single
  action:
    service: homeassistant.turn_on 
    entity_id: group.altan

- alias: 'VP Larm'
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.larm_vp
    from: 'off'
    to: 'on'
  action:
    service: notify.ios_jonas_iphone
    data:
      title: "Alarm VP!"
      message: "Värmepump larmar"

- alias: 'Hank Scene People Button '
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 2
      scene_data: 0
  action:
    service: notify.ios_jonas_iphone
    data:
      message: "People button triggered"

- alias: 'Hank Scene People Button Long'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 2
      scene_data: 2
  action:
    service: notify.ios_jonas_iphone
    data:
      message: "People button long triggered"     


- alias: 'Hank Scene Moon Button'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 1
      scene_data: 0
  action:
    service: notify.ios_jonas_iphone
    data:
      message: "Moon button triggered"

- alias: 'Hank Scene Moon Button Long'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 1
      scene_data: 2
  action:
    service: notify.ios_jonas_iphone
    data:
      message: "Moon button long triggered"


- alias: 'Hank Scene Off Button'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 3
      scene_data: 0
  action:
    service: switch.turn_off
    entity_id: switch.alloutsidelamps

- alias: 'Hank Scene Off Button Long'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 3
      scene_data: 2
  action:
    service: notify.ios_jonas_iphone
    data:
      message: "Off button long triggered"


- alias: 'Hank Scene On Button'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 4
      scene_data: 0
  action:
    service: notify.ios_jonas_iphone
    data:
      message: "On button triggered"

- alias: 'Hank Scene On Button Long'
  initial_state: True
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.hank_hkzwscn04_scene_controller_2
      scene_id: 4
      scene_data: 2
  action:
    service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: 286C0788970F
      ringtone_id: 11
      ringtone_vol: 3
